### ISSUE TITLE
scraper.rb:20:in `block in scrape_table': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/marion#2]
```
scraper.rb:20:in `block in scrape_table': undefined method `[]' for nil:NilClass (NoMethodError)
 	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:239:in `block in each'
 	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `upto'
 	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `each'
 	from scraper.rb:13:in `scrape_table'
 	from scraper.rb:39:in `scrape_and_follow_next_link'
 	from scraper.rb:76:in `<main>'
```

**Comment by CloCkWeRX** [comment]
And seems to have sorted itself.
